#!/usr/bin/env bash

java_options=(
    -Dtruffle.class.path.append=language/target/graaleneyj.jar
    -Dorg.graalvm.language.z.home="$PWD"
    -cp launcher/target/launcher-0.0.1-SNAPSHOT.jar
)

infile=/dev/stdin
for arg; do
    case $arg in
        --dump)
            java_options+=(
                -Dpolyglot.engine.AllowExperimentalOptions=true
                -Dgraal.Dump=Truffle:1
                -Dpolyglot.engine.BackgroundCompilation=false
                -Dpolyglot.engine.TraceCompilation=true
                -Dpolyglot.engine.TraceCompilationDetails=true
            )
            ;;
        -)
            infile=/dev/stdin
            ;;
        -*)
            printf >&2 '%s: unknown option: %s\n' "$0" "$arg"
            exit 1
            ;;
        *)
            infile=$arg
            ;;
    esac
done

exec \
    "${JAVA_HOME:?not set, must be set}/bin/java" \
    "${java_options[@]}" \
    de.lucaswerkmeister.graaleneyj.launcher.ZMain \
    < "$infile"
