#!/usr/bin/env bash

exec \
    "${JAVA_HOME:?not set, must be set}/bin/java" \
    -Dtruffle.class.path.append=language/target/graaleneyj.jar \
    -cp launcher/target/launcher-0.0.1-SNAPSHOT.jar \
    de.lucaswerkmeister.graaleneyj.launcher.ZMain
