name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '20.3.0.java11'
      - name: Install GraalPython
        run: gu install python
      - name: Build with Maven
        run: mvn -B package
