name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.1.0.java11'
      - name: Install GraalPython
        run: gu install python
      - name: Build with Maven
        run: mvn -B package
